// frontend-edge/src/components/ApiStateBadge.tsx
import { Badge } from '@chakra-ui/react'

const PlaylistList = ({ apiState }: { apiState: string }) => (
  <Badge
    ml="1"
    px={3}
    py={0.5}
    fontSize="xs"
    bg={apiState === 'open' ? 'green.400' : 'gray.400'}
    color="white"
    borderRadius="xl"
  >
    {apiState === 'open' ? 'API公開中' : 'API非公開'}
  </Badge>
)
export default PlaylistList

// frontend/components/playlists/ApiStateBadge.vue
<template>
  <v-chip small :color="apiStateColor" :class="textColor">{{
    apiState
  }}</v-chip>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  name: 'ApiStateBadge',
  props: {
    playlist: {
      type: Object,
      required: false,
      default: () => {},
    },
  },
  computed: {
    apiState(): string {
      return this.playlist?.apiState === 'open' ? 'API公開中' : 'API非公開'
    },
    apiStateColor(): string {
      return this.playlist?.apiState === 'open' ? 'blue-grey' : 'grey'
    },
    textColor(): string {
      return this.playlist?.apiState === 'open' ? 'white--text' : 'black--text'
    },
  },
})
</script>
